# flake8: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: camera_segmentation.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="camera_segmentation.proto",
    package="waymo.open_dataset",
    syntax="proto2",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x19\x63\x61mera_segmentation.proto\x12\x12waymo.open_dataset"\xda\x04\n\x12\x43\x61meraSegmentation"\xc3\x04\n\x04Type\x12\x12\n\x0eTYPE_UNDEFINED\x10\x00\x12\x14\n\x10TYPE_EGO_VEHICLE\x10\x01\x12\x0c\n\x08TYPE_CAR\x10\x02\x12\x0e\n\nTYPE_TRUCK\x10\x03\x12\x0c\n\x08TYPE_BUS\x10\x04\x12\x1c\n\x18TYPE_OTHER_LARGE_VEHICLE\x10\x05\x12\x10\n\x0cTYPE_BICYCLE\x10\x06\x12\x13\n\x0fTYPE_MOTORCYCLE\x10\x07\x12\x10\n\x0cTYPE_TRAILER\x10\x08\x12\x13\n\x0fTYPE_PEDESTRIAN\x10\t\x12\x10\n\x0cTYPE_CYCLIST\x10\n\x12\x15\n\x11TYPE_MOTORCYCLIST\x10\x0b\x12\r\n\tTYPE_BIRD\x10\x0c\x12\x16\n\x12TYPE_GROUND_ANIMAL\x10\r\x12\x1f\n\x1bTYPE_CONSTRUCTION_CONE_POLE\x10\x0e\x12\r\n\tTYPE_POLE\x10\x0f\x12\x1a\n\x16TYPE_PEDESTRIAN_OBJECT\x10\x10\x12\r\n\tTYPE_SIGN\x10\x11\x12\x16\n\x12TYPE_TRAFFIC_LIGHT\x10\x12\x12\x11\n\rTYPE_BUILDING\x10\x13\x12\r\n\tTYPE_ROAD\x10\x14\x12\x14\n\x10TYPE_LANE_MARKER\x10\x15\x12\x14\n\x10TYPE_ROAD_MARKER\x10\x16\x12\x11\n\rTYPE_SIDEWALK\x10\x17\x12\x13\n\x0fTYPE_VEGETATION\x10\x18\x12\x0c\n\x08TYPE_SKY\x10\x19\x12\x0f\n\x0bTYPE_GROUND\x10\x1a\x12\x10\n\x0cTYPE_DYNAMIC\x10\x1b\x12\x0f\n\x0bTYPE_STATIC\x10\x1c'
    ),
)


_CAMERASEGMENTATION_TYPE = _descriptor.EnumDescriptor(
    name="Type",
    full_name="waymo.open_dataset.CameraSegmentation.Type",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(name="TYPE_UNDEFINED", index=0, number=0, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_EGO_VEHICLE", index=1, number=1, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_CAR", index=2, number=2, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_TRUCK", index=3, number=3, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_BUS", index=4, number=4, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_OTHER_LARGE_VEHICLE", index=5, number=5, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_BICYCLE", index=6, number=6, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_MOTORCYCLE", index=7, number=7, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_TRAILER", index=8, number=8, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_PEDESTRIAN", index=9, number=9, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_CYCLIST", index=10, number=10, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_MOTORCYCLIST", index=11, number=11, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_BIRD", index=12, number=12, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_GROUND_ANIMAL", index=13, number=13, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="TYPE_CONSTRUCTION_CONE_POLE", index=14, number=14, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_POLE", index=15, number=15, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_PEDESTRIAN_OBJECT", index=16, number=16, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_SIGN", index=17, number=17, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_TRAFFIC_LIGHT", index=18, number=18, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_BUILDING", index=19, number=19, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_ROAD", index=20, number=20, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_LANE_MARKER", index=21, number=21, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="TYPE_ROAD_MARKER", index=22, number=22, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_SIDEWALK", index=23, number=23, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(
            name="TYPE_VEGETATION", index=24, number=24, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(name="TYPE_SKY", index=25, number=25, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_GROUND", index=26, number=26, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_DYNAMIC", index=27, number=27, serialized_options=None, type=None),
        _descriptor.EnumValueDescriptor(name="TYPE_STATIC", index=28, number=28, serialized_options=None, type=None),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=73,
    serialized_end=652,
)
_sym_db.RegisterEnumDescriptor(_CAMERASEGMENTATION_TYPE)


_CAMERASEGMENTATION = _descriptor.Descriptor(
    name="CameraSegmentation",
    full_name="waymo.open_dataset.CameraSegmentation",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[
        _CAMERASEGMENTATION_TYPE,
    ],
    serialized_options=None,
    is_extendable=False,
    syntax="proto2",
    extension_ranges=[],
    oneofs=[],
    serialized_start=50,
    serialized_end=652,
)

_CAMERASEGMENTATION_TYPE.containing_type = _CAMERASEGMENTATION
DESCRIPTOR.message_types_by_name["CameraSegmentation"] = _CAMERASEGMENTATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraSegmentation = _reflection.GeneratedProtocolMessageType(
    "CameraSegmentation",
    (_message.Message,),
    dict(
        DESCRIPTOR=_CAMERASEGMENTATION,
        __module__="camera_segmentation_pb2"
        # @@protoc_insertion_point(class_scope:waymo.open_dataset.CameraSegmentation)
    ),
)
_sym_db.RegisterMessage(CameraSegmentation)


# @@protoc_insertion_point(module_scope)
