from paralleldomain.decoding.nuscenes.common import NUSCENES_IMU_TO_INTERNAL_CS

DGP_DATASET_PATH_ENV = "DATASET_PATH"
CITYSCAPES_DATASET_PATH_ENV = "CITYSCAPES_PATH_ENV"
NUIMAGES_DATASET_PATH_ENV = "NUIMAGES_PATH_ENV"
NUSCENES_MINI_DATASET_PATH_ENV = "NUSCENES_MINI_PATH_ENV"
NUSCENES_TRAINVAL_DATASET_PATH_ENV = "NUSCENES_TRAINVAL_PATH_ENV"
