from paralleldomain.model.annotation import AnnotationTypes
from paralleldomain.model.class_mapping import ClassDetail

PD_CLASS_DETAILS_JSON = [
    {"name": "Animal", "id": 0, "color": {"r": 220, "g": 20, "b": 180}, "isthing": True, "supercategory": ""},
    {"name": "Bicycle", "id": 1, "color": {"r": 119, "g": 11, "b": 32}, "isthing": True, "supercategory": ""},
    {"name": "Bicyclist", "id": 2, "color": {"r": 64, "g": 64, "b": 64}, "isthing": True, "supercategory": ""},
    {"name": "Building", "id": 3, "color": {"r": 70, "g": 70, "b": 70}, "isthing": False, "supercategory": ""},
    {"name": "Bus", "id": 4, "color": {"r": 0, "g": 60, "b": 100}, "isthing": True, "supercategory": ""},
    {"name": "Car", "id": 5, "color": {"r": 0, "g": 0, "b": 142}, "isthing": True, "supercategory": ""},
    {"name": "Caravan/RV", "id": 6, "color": {"r": 0, "g": 0, "b": 90}, "isthing": True, "supercategory": ""},
    {
        "name": "ChannelizingDevice",
        "id": 60,
        "color": {"r": 237, "g": 190, "b": 120},
        "isthing": True,
        "supercategory": "",
    },
    {
        "name": "ConstructionVehicle",
        "id": 7,
        "color": {"r": 32, "g": 32, "b": 32},
        "isthing": True,
        "supercategory": "",
    },
    {"name": "CrossWalk", "id": 8, "color": {"r": 255, "g": 255, "b": 255}, "isthing": True, "supercategory": ""},
    {"name": "Debris", "id": 53, "color": {"r": 80, "g": 41, "b": 21}, "isthing": True, "supercategory": ""},
    {"name": "Fence", "id": 9, "color": {"r": 190, "g": 153, "b": 153}, "isthing": False, "supercategory": ""},
    {
        "name": "Fence(Transparent)",
        "id": 42,
        "color": {"r": 85, "g": 75, "b": 75},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "Fog(Noise)", "id": 227, "color": {"r": 114, "g": 0, "b": 255}, "isthing": False, "supercategory": ""},
    {"name": "HorizontalPole", "id": 10, "color": {"r": 153, "g": 153, "b": 153}, "isthing": True, "supercategory": ""},
    {"name": "LaneMarking", "id": 11, "color": {"r": 220, "g": 220, "b": 220}, "isthing": False, "supercategory": ""},
    {
        "name": "LaneMarking(Parking)",
        "id": 55,
        "color": {"r": 210, "g": 210, "b": 210},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "LaneMarking(ParkingIndicator)",
        "id": 56,
        "color": {"r": 210, "g": 220, "b": 210},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "LaneMarkingGap", "id": 41, "color": {"r": 0, "g": 255, "b": 255}, "isthing": False, "supercategory": ""},
    {
        "name": "LaneMarkingOther",
        "id": 40,
        "color": {"r": 255, "g": 255, "b": 0},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "LaneMarkingSpan", "id": 61, "color": {"r": 0, "g": 180, "b": 255}, "isthing": False, "supercategory": ""},
    {"name": "LimitLine", "id": 12, "color": {"r": 180, "g": 180, "b": 180}, "isthing": False, "supercategory": ""},
    {"name": "Motorcycle", "id": 13, "color": {"r": 0, "g": 0, "b": 230}, "isthing": True, "supercategory": ""},
    {"name": "Motorcyclist", "id": 14, "color": {"r": 128, "g": 128, "b": 128}, "isthing": True, "supercategory": ""},
    {
        "name": "Multipath(Noise)",
        "id": 225,
        "color": {"r": 70, "g": 255, "b": 20},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "OtherDriveableSurface",
        "id": 15,
        "color": {"r": 80, "g": 0, "b": 0},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "OtherFixedStructure",
        "id": 16,
        "color": {"r": 150, "g": 0, "b": 0},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "OtherMovable", "id": 17, "color": {"r": 230, "g": 0, "b": 0}, "isthing": True, "supercategory": ""},
    {"name": "OtherPole", "id": 45, "color": {"r": 200, "g": 200, "b": 200}, "isthing": False, "supercategory": ""},
    {"name": "OtherRider", "id": 18, "color": {"r": 192, "g": 192, "b": 192}, "isthing": True, "supercategory": ""},
    {
        "name": "Overpass/Bridge/Tunnel",
        "id": 19,
        "color": {"r": 150, "g": 100, "b": 100},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "OwnCar(EgoCar)",
        "id": 20,
        "color": {"r": 128, "g": 230, "b": 128},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "ParkingLot", "id": 48, "color": {"r": 104, "g": 27, "b": 83}, "isthing": False, "supercategory": ""},
    {"name": "ParkingMeter", "id": 21, "color": {"r": 32, "g": 32, "b": 32}, "isthing": False, "supercategory": ""},
    {"name": "ParkingSpot", "id": 63, "color": {"r": 84, "g": 155, "b": 205}, "isthing": True, "supercategory": ""},
    {"name": "Pedestrian", "id": 22, "color": {"r": 220, "g": 20, "b": 60}, "isthing": True, "supercategory": ""},
    {"name": "Powerline", "id": 46, "color": {"r": 32, "g": 32, "b": 32}, "isthing": False, "supercategory": ""},
    {"name": "Railway", "id": 23, "color": {"r": 230, "g": 150, "b": 140}, "isthing": False, "supercategory": ""},
    {"name": "Rain(Noise)", "id": 228, "color": {"r": 105, "g": 255, "b": 255}, "isthing": False, "supercategory": ""},
    {"name": "Road", "id": 24, "color": {"r": 128, "g": 64, "b": 128}, "isthing": False, "supercategory": ""},
    {"name": "RoadBarriers", "id": 25, "color": {"r": 80, "g": 80, "b": 80}, "isthing": False, "supercategory": ""},
    {
        "name": "RoadBoundary(Curb)",
        "id": 26,
        "color": {"r": 100, "g": 100, "b": 100},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "RoadBoundary(CurbFlat)",
        "id": 54,
        "color": {"r": 120, "g": 120, "b": 120},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "RoadBoundary(CurbRoadLevel)",
        "id": 66,
        "color": {"r": 140, "g": 180, "b": 140},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "Wall",
        "id": 69,
        "color": {"r": 12, "g": 150, "b": 110},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "RoadBoundary(CurbSide)",
        "id": 65,
        "color": {"r": 140, "g": 160, "b": 140},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "RoadBoundary(CurbTop)",
        "id": 64,
        "color": {"r": 140, "g": 140, "b": 140},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "RoadMarking", "id": 27, "color": {"r": 255, "g": 220, "b": 0}, "isthing": False, "supercategory": ""},
    {
        "name": "RoadMarkingArrows",
        "id": 57,
        "color": {"r": 228, "g": 190, "b": 60},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "RoadMarkingBottsDots",
        "id": 58,
        "color": {"r": 228, "g": 120, "b": 49},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "RoadMarkingSpeed",
        "id": 49,
        "color": {"r": 228, "g": 150, "b": 49},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "SchoolBus", "id": 47, "color": {"r": 15, "g": 123, "b": 122}, "isthing": True, "supercategory": ""},
    {"name": "SideWalk", "id": 28, "color": {"r": 244, "g": 35, "b": 232}, "isthing": False, "supercategory": ""},
    {"name": "Sky", "id": 29, "color": {"r": 70, "g": 130, "b": 180}, "isthing": False, "supercategory": ""},
    {
        "name": "StaticObject(BikeRack)",
        "id": 62,
        "color": {"r": 75, "g": 0, "b": 75},
        "isthing": True,
        "supercategory": "",
    },
    {
        "name": "StaticObject(Trashcan)",
        "id": 43,
        "color": {"r": 75, "g": 0, "b": 0},
        "isthing": True,
        "supercategory": "",
    },
    {"name": "StopLine", "id": 59, "color": {"r": 180, "g": 150, "b": 150}, "isthing": False, "supercategory": ""},
    {
        "name": "TemporaryConstructionObject",
        "id": 30,
        "color": {"r": 255, "g": 160, "b": 20},
        "isthing": True,
        "supercategory": "",
    },
    {"name": "Terrain", "id": 31, "color": {"r": 81, "g": 0, "b": 81}, "isthing": False, "supercategory": ""},
    {
        "name": "ThermalNoise(Noise)",
        "id": 226,
        "color": {"r": 0, "g": 255, "b": 140},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "TowedObject", "id": 32, "color": {"r": 0, "g": 0, "b": 110}, "isthing": True, "supercategory": ""},
    {"name": "TrafficLight", "id": 33, "color": {"r": 250, "g": 170, "b": 30}, "isthing": True, "supercategory": ""},
    {"name": "TrafficSign", "id": 34, "color": {"r": 220, "g": 220, "b": 0}, "isthing": True, "supercategory": ""},
    {"name": "Train", "id": 35, "color": {"r": 0, "g": 80, "b": 100}, "isthing": True, "supercategory": ""},
    {"name": "Truck", "id": 36, "color": {"r": 0, "g": 0, "b": 70}, "isthing": True, "supercategory": ""},
    {"name": "Vegetation", "id": 37, "color": {"r": 107, "g": 142, "b": 35}, "isthing": False, "supercategory": ""},
    {"name": "Vegetation(Bush)", "id": 44, "color": {"r": 54, "g": 71, "b": 18}, "isthing": False, "supercategory": ""},
    {
        "name": "Vegetation(Grass)",
        "id": 51,
        "color": {"r": 47, "g": 106, "b": 45},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "Vegetation(GroundCover)",
        "id": 50,
        "color": {"r": 35, "g": 46, "b": 11},
        "isthing": False,
        "supercategory": "",
    },
    {
        "name": "Vegetation(Tree)",
        "id": 52,
        "color": {"r": 107, "g": 142, "b": 35},
        "isthing": False,
        "supercategory": "",
    },
    {"name": "VerticalPole", "id": 38, "color": {"r": 153, "g": 153, "b": 153}, "isthing": True, "supercategory": ""},
    {"name": "Void", "id": 255, "color": {"r": 0, "g": 0, "b": 0}, "isthing": False, "supercategory": ""},
    {"name": "WheeledSlow", "id": 39, "color": {"r": 0, "g": 64, "b": 64}, "isthing": True, "supercategory": ""},
]
PD_CLASS_DETAILS = [
    ClassDetail(
        name=c["name"],
        id=c["id"],
        instanced=c["isthing"],
        meta=dict(supercategory=c["supercategory"], color=c["color"]),
    )
    for c in PD_CLASS_DETAILS_JSON
]
