# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: artifacts.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import paralleldomain.common.dgp.v1.proto.dataset_pb2 as dataset__pb2
import paralleldomain.common.dgp.v1.proto.remote_pb2 as remote__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
    name="artifacts.proto",
    package="dgp.proto",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x0f\x61rtifacts.proto\x12\tdgp.proto\x1a\rdataset.proto\x1a\x0cremote.proto"\x83\x01\n\x10\x44\x61tasetArtifacts\x12,\n\x08metadata\x18\x01 \x01(\x0b\x32\x1a.dgp.proto.DatasetMetadata\x12+\n\x08\x61rtifact\x18\x02 \x01(\x0b\x32\x19.dgp.proto.RemoteArtifact\x12\x14\n\x0c\x64\x65rived_from\x18\x03 \x03(\tb\x06proto3'
    ),
    dependencies=[
        dataset__pb2.DESCRIPTOR,
        remote__pb2.DESCRIPTOR,
    ],
)


_DATASETARTIFACTS = _descriptor.Descriptor(
    name="DatasetArtifacts",
    full_name="dgp.proto.DatasetArtifacts",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="metadata",
            full_name="dgp.proto.DatasetArtifacts.metadata",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="artifact",
            full_name="dgp.proto.DatasetArtifacts.artifact",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="derived_from",
            full_name="dgp.proto.DatasetArtifacts.derived_from",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=60,
    serialized_end=191,
)

_DATASETARTIFACTS.fields_by_name["metadata"].message_type = dataset__pb2._DATASETMETADATA
_DATASETARTIFACTS.fields_by_name["artifact"].message_type = remote__pb2._REMOTEARTIFACT
DESCRIPTOR.message_types_by_name["DatasetArtifacts"] = _DATASETARTIFACTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatasetArtifacts = _reflection.GeneratedProtocolMessageType(
    "DatasetArtifacts",
    (_message.Message,),
    dict(
        DESCRIPTOR=_DATASETARTIFACTS,
        __module__="artifacts_pb2"
        # @@protoc_insertion_point(class_scope:dgp.proto.DatasetArtifacts)
    ),
)
_sym_db.RegisterMessage(DatasetArtifacts)


# @@protoc_insertion_point(module_scope)
