from pd.internal.proto.keystone.generated.wrapper import pd_unified_generator_pb2

EgoAgentGeneratorParameters = pd_unified_generator_pb2.EgoAgentGeneratorParameters
AgentType = pd_unified_generator_pb2.AgentType
