from pd.internal.proto.keystone.generated.wrapper import pd_unified_generator_pb2

AgentSpawnData = pd_unified_generator_pb2.AgentSpawnData
VehicleSpawnData = pd_unified_generator_pb2.VehicleSpawnData
PedestrianSpawnData = pd_unified_generator_pb2.PedestrianSpawnData
DroneSpawnData = pd_unified_generator_pb2.DroneSpawnData
