# flake8: noqa
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dgp/proto/point_cloud.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2

from paralleldomain.common.dgp.v1.src.dgp.proto import geometry_pb2 as dgp_dot_proto_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x64gp/proto/point_cloud.proto\x12\tdgp.proto\x1a\x19google/protobuf/any.proto\x1a\x18\x64gp/proto/geometry.proto\"\xc2\x04\n\nPointCloud\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12;\n\x0b\x61nnotations\x18\x02 \x03(\x0b\x32&.dgp.proto.PointCloud.AnnotationsEntry\x12\x35\n\x08metadata\x18\x03 \x03(\x0b\x32#.dgp.proto.PointCloud.MetadataEntry\x12\x37\n\x0cpoint_format\x18\x04 \x03(\x0e\x32!.dgp.proto.PointCloud.ChannelType\x12\x14\n\x0cpoint_fields\x18\x05 \x03(\t\x12\x1d\n\x04pose\x18\x06 \x01(\x0b\x32\x0f.dgp.proto.Pose\x1a\x32\n\x10\x41nnotationsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\"\xc4\x01\n\x0b\x43hannelType\x12\x05\n\x01X\x10\x00\x12\x05\n\x01Y\x10\x01\x12\x05\n\x01Z\x10\x02\x12\r\n\tINTENSITY\x10\x03\x12\x05\n\x01R\x10\x04\x12\x05\n\x01G\x10\x05\x12\x05\n\x01\x42\x10\x06\x12\x08\n\x04RING\x10\x07\x12\x0c\n\x08NORMAL_X\x10\x08\x12\x0c\n\x08NORMAL_Y\x10\t\x12\x0c\n\x08NORMAL_Z\x10\n\x12\x0c\n\x08\x43LASS_ID\x10\x0b\x12\x0f\n\x0bINSTANCE_ID\x10\x0c\x12\r\n\tTIMESTAMP\x10\r\x12\x0b\n\x07\x41ZIMUTH\x10\x0e\x12\r\n\tELEVATION\x10\x0f\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dgp.proto.point_cloud_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POINTCLOUD_ANNOTATIONSENTRY']._options = None
  _globals['_POINTCLOUD_ANNOTATIONSENTRY']._serialized_options = b'8\001'
  _globals['_POINTCLOUD_METADATAENTRY']._options = None
  _globals['_POINTCLOUD_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_POINTCLOUD']._serialized_start=96
  _globals['_POINTCLOUD']._serialized_end=674
  _globals['_POINTCLOUD_ANNOTATIONSENTRY']._serialized_start=354
  _globals['_POINTCLOUD_ANNOTATIONSENTRY']._serialized_end=404
  _globals['_POINTCLOUD_METADATAENTRY']._serialized_start=406
  _globals['_POINTCLOUD_METADATAENTRY']._serialized_end=475
  _globals['_POINTCLOUD_CHANNELTYPE']._serialized_start=478
  _globals['_POINTCLOUD_CHANNELTYPE']._serialized_end=674
# @@protoc_insertion_point(module_scope)
